# Generated by Django 2.1.1 on 2018-09-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
